---
title: "Charles Manson PreTest"
output: html_document
---
```{r Initialisierung der Packages}
library(knitr)
library(igraph)
library(igraphdata)
library(rmarkdown)
library(shiny)
library(shinythemes)
library(dplyr)
library(readr)
library(intergraph)
```


```{r Einlesung der Daten}
el <- read.csv("https://raw.githubusercontent.com/226305Netzwerke/PreTest/master/226305_Projekt_CharlesManson_Edgelist.csv", header=T, as.is=T, sep = ",")
nl <- read.csv("https://raw.githubusercontent.com/226305Netzwerke/PreTest/master/226305_Projekt_CharlesManson_Nodelist.csv", header=T, as.is=T, sep = ",")
edgematrix <- as.matrix(el)


s <- graph_from_data_frame(d=edgematrix, vertices = nl, directed=T)
s
```

```{r Plotten der Rohdaten}
plot(s)
```


```{r Testplots}

plot(s,
     edge.arrow.size=0.1,
     edge.curved=0.2,
     edge.color="black",
     layout=layout_with_kk,
     main="Manson PreTest",)
plot(s,
     edge.arrow.size=0.1,
     edge.curved=0.2,
     edge.color="black",
     layout=layout.auto,
     main="Manson PreTest",)

plot(s,
     edge.arrow.size=0.1,
     edge.curved=0.2,
     edge.color="black",
     layout=layout_nicely,
     main="Manson PreTest",)
plot(s,
     edge.arrow.size=0.1,
     edge.curved=0.2,
     edge.color="black",
     layout=layout.drl,
     main="Manson PreTest",)
```


```{r Entzerrter Plot}
coords <- layout.auto(s)*2

par(mfrow=c(1,1), mar=c(0,0,3,0))

plot(s, 
     layout=coords, 
     rescale=FALSE,
     ylim=c(-4.6,7.5),
     xlim=c(-2.5,1.5), 
     asp= 0.5,
     edge.width = 0.7,
     edge.curved=TRUE, 
     vertex.size=12, 
     vertex.label.font=2,
     vertex.label.dist=5,
     vertex.label.degree = pi/2, 
     vertex.label.cex=.5,
     vertex.label.family = "Arial",
     edge.arrow.size=0.2,
     main="Manson",
     sub="Pre-Test")
```

